#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 3
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
  grey = '#6c6c6c'
  pyblue = '#4B8BBE'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '{{ .Path }}'
    foreground = 'lightBlue'
    background = 'transparent'

    [blocks.segments.properties]
      style = 'full'
      cache_duration = 'none'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    foreground = 'p:grey'
    background = 'transparent'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ end }} '
    foreground = 'p:pyblue'
    background = 'transparent'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'

    [blocks.segments.properties]
      threshold = 1000
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '❯'
    foreground_templates = [
      '{{if gt .Code 0}}red{{end}}',
      '{{if eq .Code 0}}magenta{{end}}',
    ]
    background = 'transparent'

    [blocks.segments.properties]
      cache_duration = 'none'

[transient_prompt]
  template = '❯ '
  foreground_templates = [
    '{{if gt .Code 0}}red{{end}}',
    '{{if eq .Code 0}}magenta{{end}}',
  ]
  background = 'transparent'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'
