---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# See https://prek.j178.dev to learn about prek

# exclude: ""

# pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=2000, --enforce-all]
      - id: check-json
        exclude: "dotfiles/vscode/settings.json"
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: "dotfiles/config/karabiner/karabiner.json"
      - id: trailing-whitespace

  # shellcheck
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 99470f5e12208ff0fb17ab81c3c494f7620a1d8d # frozen: v0.11.0
    hooks:
      - id: shellcheck
        types: [shell]
        args: [--external-sources, --exclude=SC1091]
        exclude: "dotfiles/shell/zsh/.zshrc"

  # actionlint
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # frozen: v1.7.12
    hooks:
      - id: actionlint

  # zizmor
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 067260dc5fe6ea86b7551bfd6f8b3ba4e6c93129 # frozen: v1.28.0
    hooks:
      - id: zizmor

  # yamllint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530 # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: [--config-file=.github/linters/.yamllint.yml, --strict]

  # betterleaks
  - repo: https://github.com/betterleaks/betterleaks
    rev: 6381fa45ae946c588e2e1334d8396a15e5171ad6 # frozen: v1.7.0
    hooks:
      - id: betterleaks

  # codespell
  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8 # frozen: v2.4.3
    hooks:
      - id: codespell
        exclude: "dotfiles/config"

  # nixfmt
  - repo: local
    hooks:
      - id: run-nixfmt
        name: nixfmt
        language: system
        entry: nixfmt
        types: [nix]

  # prettier
  - repo: local
    hooks:
      - id: run-prettier
        name: prettier
        language: system
        entry: |
          prettier --write .
