---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE:
  - SPELL

GITHUB_COMMENT_REPORTER: true
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: true

ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: .github/linters/.ansible-lint.yml
BASH_SHELLCHECK_ARGUMENTS: --external-sources --exclude=SC1091 # not-following
BASH_SHFMT_ARGUMENTS: --indent 4 --space-redirects
COPYPASTE_JSCPD_DISABLE_ERRORS: true
JSON_FILTER_REGEX_EXCLUDE: (dotfiles/vscode/settings\.json)
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (.github/PULL_REQUEST_TEMPLATE\.md)
REPOSITORY_KICS_DISABLE_ERRORS: true
YAML_YAMLLINT_ARGUMENTS: --strict
