---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE:
  - SPELL
DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD
  - REPOSITORY_KICS

FLAVOR_SUGGESTIONS: false
GITHUB_COMMENT_REPORTER: true
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: true

BASH_SHELLCHECK_ARGUMENTS: --external-sources --exclude=SC1091 # not-following
BASH_SHFMT_ARGUMENTS: --indent 4 --space-redirects
JSON_FILTER_REGEX_EXCLUDE: (^dotfiles/vscode/settings\.json$)
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (^\.github/PULL_REQUEST_TEMPLATE\.md$)
YAML_YAMLLINT_ARGUMENTS: --strict
