---
name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Run megalinter
        uses: oxsecurity/megalinter@v8
        env:
          ENABLE_LINTERS: YAML_YAMLLINT,ANSIBLE_ANSIBLE_LINT
          DEFAULT_WORKSPACE: ansible
          YAML_YAMLLINT_ARGUMENTS: --strict
          YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml
          ANSIBLE_ANSIBLE_LINT_ARGUMENTS: --strict
          ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: .ansible-lint.yml

  nix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run nix format
        uses: daniel-mizsak/workflows/.github/actions/nix-format@main

      - name: Create files to make the flake valid
        run: |
          sudo mkdir -p {/etc/nixos,/home/damz}
          echo '{ config, ... }:

          {
            fileSystems."/" = {
              device = "/dev/disk/by-uuid/00000000-0000-0000-0000-000000000000";
              fsType = "ext4";
            };
          }' | sudo tee /etc/nixos/hardware-configuration.nix
          sudo ln -s  $GITHUB_WORKSPACE/ /home/damz/mtjd

      - name: Run nix flake check
        run: >
          nix flake check --impure ./nix
