---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * 6" # Every Saturday at 12:00

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prek:
    permissions:
      contents: read
    uses: daniel-mizsak/workflows/.github/workflows/prek.yml@6fe0b2d7b995be2cf288f1603c769f0cbf26b239 # v2.2.0
    with:
      skip: "shellcheck, run-nixfmt, run-prettier"

  lint:
    permissions:
      contents: read
      pull-requests: write
    uses: daniel-mizsak/workflows/.github/workflows/lint.yml@6fe0b2d7b995be2cf288f1603c769f0cbf26b239 # v2.2.0
    with:
      megalinter-config: "./.github/linters/.megalinter.yml"

  nix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Nix install and format
        uses: daniel-mizsak/workflows/.github/actions/nix-format@6fe0b2d7b995be2cf288f1603c769f0cbf26b239 # v2.2.0

      - name: Create files to make the flake valid
        run: |
          sudo mkdir -p {/etc/nixos,/home/damz}
          echo '{ config, ... }:

          {
            fileSystems."/" = {
              device = "/dev/disk/by-label/nixos";
              fsType = "ext4";
            };
          }' | sudo tee /etc/nixos/hardware-configuration.nix
          sudo ln -s "$GITHUB_WORKSPACE/" /home/damz/mtjd

      - name: Run nix flake check
        run: >
          nix flake check --impure ./nix
