---
name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Use megalinter
        uses: oxsecurity/megalinter/flavors/cupcake@v8.7.0
        env:
          ENABLE: BASH,ACTION,ANSIBLE
          ENABLE_LINTERS: YAML_YAMLLINT,REPOSITORY_GIT_DIFF,REPOSITORY_GITLEAKS
          BASH_SHFMT_ARGUMENTS: --indent 4 --space-redirects
          BASH_SHELLCHECK_ARGUMENTS: --external-sources --exclude=SC1091
          ANSIBLE_ANSIBLE_LINT_ARGUMENTS: --strict --exclude playbook.yml

      - name: Run yamllint
        uses: daniel-mizsak/workflows/.github/actions/yaml-lint@v1

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: ansible
          setup_python: true
          args: --strict --exclude playbook.yml

      - name: Run shell linter
        uses: luizm/action-sh-checker@v0.9.0
        env:
          SHELLCHECK_OPTS: --external-sources --exclude=SC1091
          SHFMT_OPTS: --indent 4 --space-redirects

  nix:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Run nix format
        uses: daniel-mizsak/workflows/.github/actions/nix-format@v1

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Create files to make the flake valid
        run: |
          sudo mkdir -p {/etc/nixos,/home/damz}
          echo '{ config, ... }:

          {
            fileSystems."/" = {
              device = "/dev/disk/by-uuid/00000000-0000-0000-0000-000000000000";
              fsType = "ext4";
            };
          }' | sudo tee /etc/nixos/hardware-configuration.nix
          sudo ln -s "$GITHUB_WORKSPACE/" /home/damz/mtjd

      - name: Run nix flake check
        run: >
          nix flake check --impure ./nix
